app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::model('sports', 'Sport');
Route::model('players', 'Player');

Route::resource('players', 'PlayersController');
Route::resource('sports', 'SportsController');


Route::bind('sports', function($value, $route) {
    return App\Sport::whereSlug($value)->first();
});

Route::bind('players', function($value, $route) {
    return App\Player::whereSlug($value)->first();
});

Route::get('/api/v1/sports', 'ApiSportsController@index');
Route::get('/api/v1/sports/{slug}', 'ApiSportsController@index');

Route::get('/api/v1/players', 'ApiPlayersController@index');
Route::get('/api/v1/players/{slug}', 'ApiPlayersController@index');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DX Solutions</title>

    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/dxsolutions.css') }}" rel="stylesheet">

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">DX Solutions</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/sports') }}">Sports</a></li>
                    <li><a href="{{ url('/players') }}">Players</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>{!! link_to_route('sports.create', 'Create Sport') !!}</li>
                    <li>{!! link_to_route('players.create', 'Create player') !!}</li>
                </ul>
            </div>
        </div>
    </nav>

    @if (Session::has('message'))
    <div class="flash alert-info">
        <p>{{ Session::get('message') }}</p>
    </div>
    @endif

    @if ($errors->any())
    <div class='flash alert-danger'>
        @foreach ( $errors->all() as $error )
        <p>{{ $error }}</p>
        @endforeach
    </div>
    @endif

    @yield('content')

</div>
<!-- Scripts -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection